name: hee-lint

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  hee-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hee-lint (error mode)
        run: tooling/ci/hee-lint
